version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Ol@117844
      POSTGRES_USER: postgres
      POSTGRES_DB: DocStorage
      POSTGRES_PORT: 5433
    ports:
      - 5433:5433
    volumes:
      - db_data:/usr/local/var/postgres95
  app:
    image: my-node-app
    ports:
      - 5050:5050
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db_data:
